name: CI

on:
  pull_request:
  push:
    branches: ["master"]

permissions:
  checks: write
  id-token: write
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install --legacy-peer-deps
      - run: |
          npm run lint
      - run: |
          npm run coverage
      - uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
      - run: |
          npx pkg-pr-new publish
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      # https://github.com/googleapis/release-please-action
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          # https://github.com/googleapis/release-please-action?tab=readme-ov-file#github-credentials
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
