# IMPORTANT: DO NOT RENAME THIS FILE
# It uses Trusted Publisher to deploy without token
# https://www.npmjs.com/package/serverless-step-functions/access

name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write # needed for npm publish with provenance

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install --legacy-peer-deps
      - run: |
          npm run lint
      - run: |
          npm run test
      - run: |
          npm publish --provenance
